export declare const labelMessages: {
    lbl: {
        type: string;
        audience: string;
        eventtype: string;
        startdate: string;
        previous: string;
        next: string;
        search: string;
        changefilters: string;
        reset: string;
        apply: string;
        by: string;
        datetime: string;
        join: string;
        online: string;
        offline: string;
        pages: string;
        collaborators: string;
        dialcode: string;
        onlineproviderdata: string;
        provider: string;
        createnewevent: string;
        startdatetime: string;
        enddatetime: string;
        registrationstartdate: string;
        registrationenddate: string;
        save: string;
        cancel: string;
        edit: string;
        retire: string;
        enroll: string;
        unenroll: string;
    };
};
